name: "Moabi"
description: "Moabi is a collaborative mapping platform to monitor landuse planning in the Democratic Republic of the Congo."
baseurl:
permalink: /:title
prose:
  rooturl: '_posts'
  siteurl: 'rdc.moabi.org'
  metadata:
    _posts/prose_project/:
      - name: "layout"
        field:
          element: "hidden"
          value: "prose_project"
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish?"
          value: true
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: "/prose_projects/...html"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "map_lat"
        field:
          element: "text"
          label: "Map Center Latitude"
      - name: "map_lon"
        field:
          element: "text"
          label: "Map Center Longitude"
      - name: "map_zoom"
        field:
          element: "text"
          label: "Map Zoom"
      - name: "basemap"
        field:
          element: "text"
          label: "Base Map"

      - name: "about_header"
        field:
          element: "text"
          label: "About Text Header"
      - name: "data_header"
        field:
          element: "text"
          label: "Data Text Header"
      - name: "data_description"
        field:
          element: "textarea"
          label: "Data Text Description"
          value: description...
      - name: "data_layer1_name"
        field:
          element: "text"
          label: "Name of First Data Layer"
      - name: "data_layer1_id"
        field:
          element: "text"
          label: "Map ID of First Data Layer"
      - name: "data_layer2_name"
        field:
          element: "text"
          label: "Name of Second Data Layer"
      - name: "data_layer2_id"
        field:
          element: "text"
          label: "Map ID of Second Data Layer"
    _posts/prose_project/:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog_post"
      - name: "categories"
        field:
          element: "hidden"
          value: "[blog_post]"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "subtitle"
        field:
          element: "text"
          label: "Title"



