name: "Moabi"
description: "Moabi is a collaborative mapping platform to monitor landuse planning in the Democratic Republic of the Congo."
baseurl:
permalink: /:title
prose:
  rooturl: '_posts'
  siteurl: 'rdc.moabi.org'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "prose_project"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
            - name: "Pears"
              value: "pears"
            - name: "Mangos"
              value: "mangos"
