name: "Moabi"
description: "Moabi is a collaborative mapping platform to monitor landuse planning in the Democratic Republic of the Congo."
baseurl: /site
permalink: /:title/:categories/
markdown: kramdown
